# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: New York by Night Transcripts
description: An unofficial collection of transcripts for New York by Night, created by <a href="https://mqole.tumblr.com" target="_blank">mqole</a>.
baseurl: "/vtmTranscripts"
url: "https://mqole.github.io"
github_username: mqole

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
logo: "/assets/images/logo.png"

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GitHub page":
    - "//github.com/mqole/vtmTranscripts"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  - title: GitHub page
    url: https://github.com/mqole/vtmTranscripts
  - title: Watch NYbN on YouTube
    url: https://youtube.com/playlist?list=PL4qzoETfmhLZDmpmGP_rs4bgstBFZmlzN

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "New York by Night and Vampire: the Masquerade are properties of World of Darkness. These transcripts are created and distributed by mqole under an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a> This site is powered by <a href=\"https://www.netlify.com/\">Netlify</a>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Footer "Edit this page on GitHub" link text
gh_edit_link: false
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/mqole/vtmTranscripts"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: vampire

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
